# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        aws.storage:
            adapter: 'aws'
            options:
                client: 'aws_s3_client'
                bucket: 'mes-collections'
                prefix: 'https://u7aw0j.stackhero-network.com'

